/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const GreetingBS = require('./Greeting.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Props = { readonly name: string };

export const Greeting: React.ComponentType<{ readonly name: string }> = GreetingBS.make;
